language: rust

rust:
  - nightly-2019-05-29

cache: cargo
env:
  - DATABASE_URL=test_app.db TEST_SERVER=https://localhost:8080 ROCKET_ENV=dev SECRET=123456

before_script:
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src
  - export RUST_TEST_THREADS=1
  - cargo install diesel_cli --force --no-default-features --features=sqlite
  - cargo install --force cargo-audit
  - rm -f test_app.db && diesel setup
  - cargo run &

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo audit
