language: rust

rust:
  - nightly-2018-09-18

cache: cargo
env:
  - DATABASE_URL=test_app.db TEST_SERVER=http://localhost:8000 DEPLOY_MODE=TEST

before_script:
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src
  - cargo install diesel_cli --no-default-features --features=sqlite
  - diesel setup

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
