[package]
authors = ["apiraino <apiraino@users.noreply.github.com>", "kkom <kkom@users.noreply.github.com>"]
name = "open-taffeta"
version = "0.1.0"

[dependencies]

# Rocket crates
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
rocket_cors = "0.2"

# FIXME: what are these for?
validator = "0.6.3"
validator_derive = "0.6.1"
rust-crypto = "0.2.36"
frank_jwt = "3.0.0"
slug = "0.1.2"
rand = "0.4.2"

# ORM crates: diesel 1.3 breaks with nightly (as of end of May 2018)
diesel = {version = "<=1.2" , features = ["chrono", "sqlite", "r2d2"]}
serde = "1.0.26"
serde_derive = "1.0.26"
serde_json = "1.0.8"

dotenv = "0.9.0"
chrono = {version = "0.4.0", features = ["serde"]}

