cargo-features = ["edition"]

[package]
authors = ["apiraino <apiraino@users.noreply.github.com>", "kkom <kkom@users.noreply.github.com>"]
name = "open-taffeta"
version = "0.1.0"
edition = '2018'

[lib]
name = "open_taffeta_lib"
path = "src/lib.rs"

[[bin]]
name = "open_taffeta_bin"
path = "src/main.rs"

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"
rocket_cors = "0.3.0"

# FIXME: what are these for?
validator = "0.7.1"
validator_derive = "0.7.2"
rust-crypto = "0.2.36"
frank_jwt = "3.0.0"
slug = "0.1.3"
rand = "0.5.5"

# ORM crates: diesel 1.3 breaks with nightly (as of end of May 2018)
diesel = { version = "1.3.2", features = ["chrono", "sqlite", "r2d2"] }

serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.24"

env_logger = "0.5.12"
log = "0.4.3"
dotenv = "0.13.0"
dotenv_codegen = "0.11.0"
chrono = { version = "0.4.5", features = ["serde"] }
reqwest = "0.8.8"

# https://vfoley.xyz/rust-compile-speed-tips/
[profile.dev]
lto=false
