[package]
authors = ["apiraino <apiraino@users.noreply.github.com>", "kkom <kkom@users.noreply.github.com>"]
name = "open-taffeta"
version = "0.1.0"
edition = "2018"

[lib]
name = "open_taffeta_lib"
path = "src/lib.rs"

[[bin]]
name = "open_taffeta_bin"
path = "src/main.rs"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json"]

[dependencies]
rocket = "0.4.0"
rocket_cors = "0.4.0-rc.3"

# validation for input struct deserialized
validator = "0.8.0"
validator_derive = "0.8.0"

rust-crypto = "0.2.36"
frank_jwt = "3.1.0"
slug = "0.1.4"

diesel = { version = "1.3.3", features = ["chrono", "sqlite", "r2d2"] }

serde = "1.0.81"
serde_derive = "1.0.81"
serde_json = "1.0.33"

env_logger = "0.6.0"
log = "0.4.6"
dotenv = "0.13.0"
dotenv_codegen = "0.11.0"
chrono = { version = "0.4.6", features = ["serde"] }
reqwest = "0.9.5"
rand = "0.6.1"

# https://vfoley.xyz/rust-compile-speed-tips/
[profile.dev]
lto=false
