[dev]
address = "localhost"
port = 8000
workers = 2
log = "normal"
# secret_key = "123456"
limits = { forms = 32768 }
# can only use this with a State in routes
# https://rocket.rs/guide/configuration/#extras
# database_url="test_app.db"

[prod]
address = "0.0.0.0"
port = 8000
workers = 4
log = "critical"
# secret_key = "aaabbbcccddd..."
limits = { forms = 32768 }
